apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-ebs

reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer #so that volume will get created at the time of pod getting created