#In dynamic Provisioning, volume will be created automatically, hence no need to create pv and no need to give volumeName

#1)PVC Creation:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "expense-ebs"
  resources:
    requests:
      storage: 3Gi

---
#2) pod creation:
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    purpose: ebs-dynamic
spec:
  nodeSelector:
    topology.kubernets.io/zone: us-east-1f
  
  containers:
  - name: nginx
    image:  nginx
    volumeMounts:
    - name: ebs-dynamic   #this volumeMounts name and volumes name both should be same
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-dynamic
    persistentVolumeClaim:
      claimName: ebs-dynamic

---

#3) Service for pods:
apiVersion: v1
kind: Service
metadata:
  name: nginx-service

spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80   #service Port
    targetPort: 80  #ContainerPort
    nodePort: 30007   # Worker Node

