apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-efs
spec:
  provisioner: efs.csi.aws.com
  
parameters:
  provisioningMode: efs-ap
  directoryPerms: "700"
  basePath: "/expense"
  fileSystemId: fs-0a9fdcb2595138329
