

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: "expense-efs"
  
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels: 
    purpose: efs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: efs-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-dynamic
    persistentVolumeClaim:
      claimName: efs-dynamic


---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80   #service Port
    targetPort: 80  #ContainerPort
    nodePort: 30007   # Worker Node



# steps:
# create efs filesystem and update this id in volumeHandle in static and fileSystemId in efs-sc.yaml
# install efs csi drivers and then in that default sg allow 2049 port nfs from ec2 instance sg grps
# in ec2 instance sg grp, open 30007 nodePort for all traffic
# allow efs csi driver policy in iam role
# create pv for static and pvc for static and only pvc for dynamic keeping filesystem alive, unlike deleting(not required) in ebs dynamic provisioning
# pod and service creation


# root@efs-dynamic:/# nslookup nginx
# ;; Got recursion not available from 10.100.0.10
# Server:         10.100.0.10
# Address:        10.100.0.10#53

# Name:   nginx.default.svc.cluster.local
# Address: 10.100.9.162
# ;; Got recursion not available from 10.100.0.10


#  349  03/11/24 16:17:45 kubectl kustomize     "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-2.1" > public-ecr-driver.yaml
#   350  03/11/24 16:18:02 ls -la
#   351  03/11/24 16:18:10 kubectl apply -f public-ecr-driver.yaml
#   352  03/11/24 16:18:23 kubectl get csidriver
#   353  03/11/24 16:19:09 kubectl get csidrivers
#   354  03/11/24 16:19:18 kubectl kustomize     "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-2.1" > public-ecr-driver.yaml
#   355  03/11/24 16:19:46 kubectl kustomize "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-2.1" > public-ecr-driver.yaml
#   356  03/11/24 16:20:20 kustomize edit fix
#   357  03/11/24 16:36:19 ls -la
#   358  03/11/24 16:36:24 kubectl apply -f public-ecr-driver.yaml
#   359  03/11/24 16:40:06 ls -la
#   360  03/11/24 16:40:14 rm public-ecr-driver.yaml
#   361  03/11/24 16:40:18 ls -la
#   362  03/11/24 16:40:45 kubectl kustomize     "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-2.1" > public-ecr-driver.yaml
#   363  03/11/24 16:40:53 ls -la
#   364  03/11/24 16:41:04 kubectl apply -f public-ecr-driver.yaml
#   365  03/11/24 16:41:19 kubectl get csidriver
#   366  03/11/24 16:41:30 kubectl get csidrivers
#   367  03/11/24 16:44:41 git pull
#   368  03/11/24 16:44:51 cd k8-resources/volumes/
#   369  03/11/24 16:44:52 git pull
#   370  03/11/24 16:44:54 cd
#   371  03/11/24 16:44:58 ls -la
#   372  03/11/24 16:45:05 kubectl apply -f public-ecr-driver.yaml
#   373  03/11/24 16:45:17 kubectl get csidriver
#   374  03/11/24 16:45:21 kubectl get csidrivers
#   375  03/11/24 16:47:39 kubectl apply -f public-ecr-driver.yaml
#   376  03/11/24 16:47:49 kubectl delete -f public-ecr-driver.yaml
#   377  03/11/24 16:48:01 kubectl apply -f public-ecr-driver.yaml
#   378  03/11/24 16:48:14 kubectl get csidrivers
#   379  03/11/24 16:48:43 cd k8-resources/volumes/
#   380  03/11/24 16:48:45 clear
#   381  03/11/24 16:48:56 kubectl get pv
#   382  03/11/24 16:49:06 kubectl apply -f 04-efs-static.yaml
#   383  03/11/24 16:49:58 kubectl delete -f 04-efs-static.yaml
#   384  03/11/24 16:56:10 cd k8-resources/volumes/
#   385  03/11/24 16:56:11 clear
#   386  03/11/24 16:56:15 kubectl get pods
#   387  03/11/24 16:56:19 kubectl get sc
#   388  03/11/24 16:56:23 kubectl get svc
#   389  03/11/24 16:56:29 kubectl get pvc
#   390  03/11/24 16:56:33 kubectl get pv
#   391  03/11/24 16:56:43 git pull
#   392  03/11/24 16:56:50 kubectl apply -f 04-efs-static.yaml
#   393  03/11/24 16:57:18 kubectl get pv
#   394  03/11/24 16:57:27 kubectl delete pv efs-static
#   395  03/11/24 17:36:01 cd k8-resources/volumes/
#   396  03/11/24 17:36:05 clear
#   397  03/11/24 17:36:11 kubectl get pv,pvc
#   398  03/11/24 17:36:27 kubectl get pvc
#   399  03/11/24 17:36:37 kubectl delete -f 04-efs-static.yaml
#   400  03/11/24 17:36:59 kubectl get pv
#   401  03/11/24 17:37:17 git pull
#   402  03/11/24 17:37:28 kubectl apply -f 04-efs-static.yaml
#   403  03/11/24 17:37:36 kubectl get pods
#   404  03/11/24 17:37:45 kubectl get pv
#   405  03/11/24 17:37:53 kubectl get pvc
#   406  03/11/24 17:38:01 kubectl get pod
#   407  03/11/24 17:38:10 kubectl get sc
#   408  03/11/24 17:38:21 kubectl get csidrivers
#   409  03/11/24 17:39:57 kubectl exec -it efs-static -- bash
#   410  03/11/24 17:41:07 kubectl apply -f 05-efs-sc.yaml
#   411  03/11/24 17:42:12 kubectl delete -f 04-efs-static.yaml
#   412  03/11/24 17:42:46 kubectl get pv,pvc
#   413  03/11/24 17:42:56 git pull
#   414  03/11/24 17:43:16 kubectl apply -f 05-efs-sc.yaml
#   415  03/11/24 17:43:24 kubectl get svc
#   416  03/11/24 17:43:31 kubectl get sc
#   417  03/11/24 17:46:18 kubectl apply -f 06-efs-dynamic.yaml
#   418  03/11/24 17:46:34 kubectl get pv
#   419  03/11/24 17:46:40 kubectl get pvc
#   420  03/11/24 17:46:45 kubectl get pods
#   421  03/11/24 17:47:05 kubectl delete -f 04-efs-static.yaml
#   422  03/11/24 17:47:14 kubectl get pods
#   423  03/11/24 17:47:20 kubectl get pvc
#   424  03/11/24 17:47:39 kubectl describe pod efs-dynamic
#   425  03/11/24 17:55:03 cd
#   426  03/11/24 17:55:05 ls -la
#   427  03/11/24 17:55:17 kubectl get csidrivers
#   428  03/11/24 17:56:38 cd k8-resources/volumes/
#   429  03/11/24 17:56:40 clear
#   430  03/11/24 17:56:43 kubectl get pods
#   431  03/11/24 17:57:30 kubectl exec -it efs-dynamic -- bash

