apiVersion: v1
kind: Pod
metadata:
  name: limits
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:        # requests are soft limits
        cpu: "100m"
        memory: "100Mi"
      limits:          # limits are hard limits
        cpu: "120m"
        memory: "200Mi"



# kubectl apply -f 07-resource-limit.yaml
# kubectl get pods
# kubectl describe pod limits -- bash