apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
data:
  username: bW9oYW5zYWkK  #should be in encoded ----> echo "mohansai" | base64
  password: YWRtaW4xMjMK  #should be in encoded ----> echo "admin123" | base64



# kubectl apply -f 10-secret.yaml
# kubectl get secrets
# kubectl describe secret pod-secret