apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret




# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     env:
#     - name: pod-secret
#       valueFrom:
#         secretKeyRef:
#           name: pod-secret
#           key: username


# kubectl apply -f 11-pod-secret.yaml
# kubectl get pods
# kubectl describe pod pod-secret
