apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80   #Service port ---> initially from user to service port or user to load balancer and then load balancer to service port
    targetPort: 80  #targetPort is the container port which is in the pod, service and containers can have different ports, but pod dont have any port
    

