apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port
spec:
  type: NodePort
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
  - name: nginx-svc-port
    port: 80
    targetPort: 80
    protocol: TCP