apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80


#load balancer will get the cluster IP and nodeport automatically.
# As it is load balancer, it will get dns name as well, using that we can fetch from external browsers