apiVersion: v1
kind: Service
metadata:
  name: nginx-load_balancer
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    module: backend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80