apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        #image: nginx
        image: nginx:stable-perl   #if version changes from empty to stable-perl, then it will restart the pods to get the new version
        #if entire image changes, then it will create new replicaset under which new pods with new image will be created then old image pods in old replicaset will be deleted, but still old replicaset will be there for rolling back purpose,
      

      
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-svc-nginx 
spec:
  selector:
    app: nginx
    tier: frontend
  ports:
  - name: deployment-svc-port
    protocol: TCP
    port: 80
    targetPort: 80


